Install these file types from the Zope3 code:
    *.rst
    *.request
    *.response

That fixes two of the test failures when running from a
WinBuilders build directory.  Two others have been failing since
last October.  That leaves one:

ERROR: testCorrectFactories (zope.app.publisher.browser.tests.test_directoryresource.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Code\build\lib\python\zope\app\publisher\browser\tests\test_directoryresource.py", line 107, in testCorrectFa
ctories
    file = resource['png']
  File "C:\Code\build\lib\python\zope\app\publisher\browser\directoryresource.py", line 77, in __getitem__
    raise KeyError, name
KeyError: 'png'

It could well be that this one fails because zope/app/publisher/browser/tests/
test_directoryresource has a bunch of goofy files in it, like indeed a file named
plain "png" with no extension.


svn path=/Zope/trunk/; revision=30197